### ISSUE TITLE
Help with Blue

### ISSUE THREAD

**Issue by konsumer** [bangcorrupt/hacktribe#267]
Hi,
Pardon me, if this is the wrong place to ask, but I have a Electribe2 (blue) that I bought specifically to install hacktribe on, and I can't figure out how to get it working with the new synths + original sounds.

I updated to hacktribe, and it seems to work (I can switch oscillators and they work great) but on standard firmware (2.02 from korg website) it has drums and lots more samples. I want both the new stuff and the old stuff.

If I understand correctly, I need to boot into original firmware, then "EXPORT ALL AUDIO", and manage it in Oe2sSLE, moving it all to 500+, but on device, I see no option to "EXPORT ALL AUDIO" in menu.

Is there another step I need to do?

**Comment by konsumer** [comment]
I also tried instructions [here](https://github.com/bangcorrupt/hacktribe/wiki/Dump-Synth-PCM-Samples) and get thsi error:

```
DEBUG:root:Initialise SysEx
Traceback (most recent call last):
  File "/Users/konsumer/Downloads/hacktribe/scripts/dump_extracted_pcm.py", line 8, in <module>
    e = E2Sysex()
        ^^^^^^^^^
  File "/Users/konsumer/Downloads/hacktribe/scripts/e2sysex.py", line 31, in __init__
    self.inport = mido.open_input(port)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mido/backends/backend.py", line 91, in open_input
    return self.module.Input(name, **self._add_api(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mido/ports.py", line 161, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mido/ports.py", line 86, in __init__
    self._open(**kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mido/backends/rtmidi.py", line 123, in _open
    rtapi = _get_api_id(api)
            ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mido/backends/rtmidi.py", line 34, in _get_api_id
    return rtmidi.API_UNSPECIFIED
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'
```

**Comment by konsumer** [comment]
I sort of got it working without the dump-script, but all the samples are out of order abnd incorrect (liek the saxes are drums.) Here is what I did:

- Load hacktribe firmware for blue (use the header patch option)
- checkout  `synth-pcm-dump` branch
- Get official sampler firmware, patch it
- Install on device
- boot with no SD, plug SD in after it's booted, "EXPORT ALL SAMPLES" (in menu now!)
- Checkout `main`, patch official sampler firmware
- Update (goes in `KORG/electribe sampler` not `KORG/electribe`)
- Now, you have `e2sSample.all` in `Samples/`, so offset start index to 500, save & copy that to `KORG/hacktribe/Samples` and boot

It definitely seems closer, but inspecting that `e2sSample.all`, it's definitely wrong. Is there any other way to extract this?
